plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.9'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.axel'
version = '0.0.1-SNAPSHOT'
description = 'PennyWise - Expense tracker API'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-security' // security
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
	implementation 'org.springframework.boot:spring-boot-starter-web' // Web + JSON
	implementation 'org.springframework.boot:spring-boot-starter-validation' // DTO input validation
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa' // Data access
	runtimeOnly 'org.postgresql:postgresql'
	implementation 'org.flywaydb:flyway-core' // Flyway for DB migrations
	runtimeOnly 'org.flywaydb:flyway-database-postgresql'
	implementation 'org.springframework.boot:spring-boot-starter-actuator' // Observability and monitoring
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.15' // OpenAPI documentation
	compileOnly 'org.projectlombok:lombok' // Lombok
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test' // Testing
	testImplementation 'org.springframework.security:spring-security-test'
	testImplementation 'org.testcontainers:junit-jupiter'
	testImplementation 'org.testcontainers:postgresql'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testImplementation 'org.springframework.boot:spring-boot-testcontainers'

}

tasks.named('test') {
	useJUnitPlatform()
}
