name: Super-Linter

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Super-Linter requires the full history to detect changes
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@v7
        env:
          # To report status for each individual linter
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Validate all files only on PRs to main branch
          VALIDATE_ALL_CODEBASE: ${{ github.base_ref == 'main' }}
          LOG_LEVEL: NOTICE
          # Disable linters not applicable to Java backend
          VALIDATE_CHECKOV: false
          VALIDATE_JSCPD: false
          VALIDATE_CLOJURE: false
          VALIDATE_COFFEESCRIPT: false
          VALIDATE_CSHARP: false
          VALIDATE_ENV: false
          VALIDATE_GHERKIN: false
          VALIDATE_JAVASCRIPT_PRETTIER: false
          VALIDATE_JSONNET: false
          VALIDATE_KOTLIN: false
          VALIDATE_LUA: false
          VALIDATE_PERL: false
          VALIDATE_PHP: false
          VALIDATE_POWERSHELL: false
          VALIDATE_PROTOBUF: false
          VALIDATE_RUBY: false
          VALIDATE_RUST: false
          VALIDATE_SCALAFMT: false
          VALIDATE_SHELL_SHFMT: false
          VALIDATE_SNAKEMAKE: false
          VALIDATE_SWIFT: false
          VALIDATE_TERRAFORM: false
          VALIDATE_TYPESCRIPT_PRETTIER: false
